config/routes.rb
Rails.application.routes.draw do
  
  root 'access#menu'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users do
     member do
      get :delete
     end
  end

  resources :questions do
     member do
      get :delete
     end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

	has_secure_password
	has_many :tests, :dependent => :destroy

	scope :sorted, lambda {order('superuser DESC, year DESC,section, roll_number, first_name, last_name')}
	
	def name
		"#{first_name} #{last_name}"
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

	before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]
	before_action :is_superuser, :except => [:login, :attempt_login, :logout]

	def menu
		@username = session[:username]
		redirect_to(questions_path)
	end

	def login
	end

	def attempt_login
		if params[:username].present? && params[:password].present?
			found_user = AdminUser.where(:username => params[:username]).first
			if found_user
				authorized_user = found_user.authenticate(params[:password])
			end
		end

		if authorized_user
			session[:user_id] = authorized_user.id
			session[:username] = authorized_user.username
			redirect_to(admin_path)
		else
			flash.now[:danger] = "Invalid username or password."
			render('login')
		end
	end

	def logout
		session[:user_id] = nil
		session[:username] = nil
		flash[:success] = 'You are logged out.'
		redirect_to(access_login_path)
	end
	
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

	before_action :confirm_logged_in
	before_action :is_superuser

	def index
		@admin_users = AdminUser.sorted
	end

	def show
		@admin_user = AdminUser.find(params[:id])
	end

	def new
		@admin_user = AdminUser.new
	end

	def create
		@admin_user = AdminUser.new(admin_user_params)
		if @admin_user.save
			flash[:success] = 'User created successfully.'
			redirect_to(admin_users_path)
		else
			render('new')
		end
	end

	def edit
		@admin_user = AdminUser.find(params[:id])
	end

	def update
		@admin_user = AdminUser.find(params[:id])
		if @admin_user.update_attributes(admin_user_params)
			flash[:success] = 'User updated successfully.'
			redirect_to(admin_users_path)
		else
			render('edit')
		end
	end

	def delete
		@admin_user = AdminUser.find(params[:id])
	end

	def destroy
		@admin_user = AdminUser.find(params[:id])
		@admin_user.destroy
		flash[:success] = 'User destroyed successfully.'
		redirect_to(admin_users_path)
	end

	private

	def admin_user_params
		params.require(:admin_user).permit(
			:first_name,
			:last_name,
			:section,
			:roll_number,
			:year,
			:email,
			:username,
			:password,
			:superuser,
			:answered,
			:score
			)
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private
	
	def confirm_logged_in
		unless session[:user_id]
			redirect_to(access_login_path)
		end
	end

	def is_superuser
		user = AdminUser.find(session[:user_id])
		unless user.superuser?
			redirect_to(tests_path)
		end
	end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # READ ACTIONS
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  # CREATE ACTIONS
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(:description=> params[:question][:description], :answer => params[:question][:answer], :one => params[:question][:one], :two => params[:question][:two], :three => params[:question][:three])
    if @question.save
      flash[:success] = "Question created successfully."
      redirect_to(questions_path)
    else
      flash[:danger].now = "Question form error."
      render 'new'
    end
  end

  # UPDATE ACTIONS
  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
      redirect_to (questions_path)
    else
      render 'edit'
    end
  end

  # DELETE ACTIONS
  def delete
    @question = Question.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:success] = "Question '#{@question.id}' deleted successfully."
    redirect_to(questions_path)
  end

  private

  def question_params
    params.require(:question).permit(:description, :answer, :one, :two, :three)
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/access/login.html.erb
<div class="center jumbotron">
  <h1>Welcome!</h1>
  <%= form_tag(access_attempt_login_path, :method => :post, :class => 'form-horizontal', :role => 'form' ) do %>
      <div class="form-group">
        <%= label_tag(:username, nil, class: 'col-sm-2 control-label') %>
        <div class="col-sm-8">
          <%= text_field_tag(:username, params[:username], :class => 'form-control', :placeholder => 'Enter Username') %>
        </div>
      </div>
      <div class="form-group">
        <br>
        <%= label_tag(:password, nil, class: 'col-sm-2 control-label') %>
        <div class="col-sm-8">
          <%= password_field_tag(:password, nil, :class => 'form-control', :placeholder => 'Enter Password') %>
        </div>
      </div>
      <br/>
      <div class="form-group">
        <div class="col-sm-6">
          <%= submit_tag("Login", :class => 'btn btn-danger btn-lg')  %>
        </div>
      </div>
  <% end %>
</div>

app/views/admin_users/_form.html.erb
<div class="form-group">
  <%= f.label :year, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :year, class: 'form-control', placeholder: 'Year of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :section, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :section, class: 'form-control', placeholder: 'Section of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :roll_number, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :roll_number, class: 'form-control', placeholder: 'Roll no. of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :first_name, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :first_name, class: 'form-control', placeholder: 'First name of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :last_name, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last name of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :email, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :email, class: 'form-control', placeholder: 'Email of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :username, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :username, class: 'form-control', placeholder: 'Username for user (required)', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :password, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :password, class: 'form-control', placeholder: 'Password for user (required for new users)', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :superuser, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.radio_button :superuser, 'true', autofocus: true %>Yes
    <%= f.radio_button :superuser, 'false', autofocus: true %>No
  </div>
</div>

app/views/admin_users/delete.html.erb
<% @page_title = "Delete User"%>
<%= form_for(@admin_user,:method => 'delete') do |f| %>
    <div class="center page-header">
      <h2>Delete [<%= f.object.username %>]?</h2>
    </div>
    <div class="center form-group">
      <p>Are you sure you want to delete this user?</p>
      <div class="col-sm-12">
        <%= f.submit "Delete User",class: 'btn btn-danger btn-lg' %>
      </div>
    </div>
<% end %>

app/views/admin_users/edit.html.erb
<% @page_title = "Update User"%>
<div class="center page-header">
  <h2>Edit User</h2>
</div>
<%= form_for @admin_user, html: { class: 'form-horizontal', role: 'form' } do |f| %>
		<%= render(:partial => 'form', :locals => {:f => f}) %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Update User",class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
<% end %>

app/views/admin_users/index.html.erb
<% @page_title = "Manage Users" %>
<div class="center page-header">
  <h2>Manage Users</h2>
  <%= pluralize(@admin_users.size, 'user') %> found
  <div class="center">
    <%= link_to("Add User", new_admin_user_path, :class => 'btn btn-primary') %>
  </div>
</div>
<div>
  <table class="table table-bordered table-striped table-hover table-condensed">
    <tr>
      <th>Year</th>
      <th>Section</th>
      <th>Roll number</th>
      <th>Name</th>
      <th>Email</th>
      <th>Username</th>
      <th>Admin</th>
      <th>Score</th>
      <th>Actions</th>
    </tr>
    <% @admin_users.each do |admin_user| %>
        <tr>
          <td><%= admin_user.year %></td>
          <td><%= admin_user.section %></td>
          <td><%= admin_user.roll_number %></td>
          <td><%= admin_user.name %></td>
          <td><%= mail_to(admin_user.email) %></td>
          <td><%= admin_user.username %></td>
          <td><%= admin_user.superuser ? 'Yes' : 'No' %></td>
          <td><%= admin_user.score %></td>
          <td>
            <%= link_to('Edit', edit_admin_user_path(admin_user), :class => 'btn btn-info btn-sm') %>
            <%= link_to('Delete', delete_admin_user_path(admin_user), :class => 'btn btn-danger btn-sm') %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/admin_users/new.html.erb
<% @page_title = "Create User"%>
<div class="center page-header">
  <h2>Create User</h2>
</div>
<%= form_for @admin_user, html: { class: 'form-horizontal', role: 'form' } do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Create User",class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
<% end %>

app/views/admin_users/show.html.erb
<% @page_title = "Scorecard"%>
<div class="center page-header">
  <h2>Scorecard for [<%= @admin_user.username %>]</h2>
</div>
<div class="well col-xs-8 col-xs-offset-2">
	<table class="table table-bordered table-striped table-hover table-condensed">
		<th class="success text-center">Test Date</th>
		<th class="success text-center">Name</th>
		<th class="success text-center">Percentage Score</th>
		<% @tests.each do |test| %>
		<tr>
			<td class="active data"> <%= test.updated_at %> </td>
			<td class="active data"> <%= test.program.name %> </td>
			<td class="info text-center object-code"> <%= test.score %> </td>
		</tr>
		<% end %>
	</table>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright &copy Rajat Pundir
  </small>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %> alert-dismissible" role="alert">
          <a href="#" class="close" data-dismiss="alert" aria-label="Close">&#215;</a>
          <%= msg %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Assembler", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <% if is_logged_in %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if user.superuser? %>
              <ul class="nav navbar-nav">
                <li><%= link_to "Manage Users", admin_users_path %></li>
                <li><%= link_to "Manage Questions", questions_path %></li>
              </ul>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <% if user.superuser? %>
                <li><%= link_to "Take Test", tests_path %></li>
            <% else %>
                <li><%= link_to user.name, tests_path %></li>
            <% end %>
            <li><%= link_to "Logout", access_logout_path %></li>
          </ul>
        </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @page_title || "Compilest" %> </title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<% user = AdminUser.where(:username => session[:username]).first %>
	<% if user %>
	<%= render 'layouts/navigation', :is_logged_in => true, :user => user %>
	<% else %>
	<%= render 'layouts/navigation', :is_logged_in => false %>
	<% end %>
	<%= render 'layouts/messages' %>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/questions/delete.html.erb
<% @page_title = "Delete Question"%>
<%= form_for(@question,:method => 'delete') do |f| %>
<div class="center page-header">
  <h2><%= f.object.description %>?</h2>
</div>
    <div class="center form-group">
      <p>Are you sure you wish to permanently delete this?</p>
      <div class="col-sm-12">
        <%= f.submit "Delete Question",class: 'btn btn-danger btn-lg' %>
      </div>
    </div>
<% end %>

app/views/questions/edit.html.erb
<% @page_title = "Create Test"%>
<div class="center page-header">
  <h2>Edit Test</h2>
</div>
	<%= form_for(@question,:url=> question_path(@question),:method => 'patch', :html => {:class => 'form-horizontal', :role => 'form'}) do |f| %>
    <div class="form-group">
        <%= f.label :description, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :description, class: 'form-control', placeholder: 'Write question description', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :answer, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :answer, class: 'form-control', placeholder: 'Write answer', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :one, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :one, class: 'form-control', placeholder: 'Enter other choice', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :two, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :two, class: 'form-control', placeholder: 'Enter other choice', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :three, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :three, class: 'form-control', placeholder: 'Enter other choice', autofocus: true %>
        </div>
      </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "OK",class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
	<% end %>

app/views/questions/index.html.erb
<% @page_title = "Manage Questions" %>
<div class="center page-header">
  <h2>Manage Questions</h2>
  <%= link_to "Add new Question", new_question_path, :class => 'btn btn-primary' %>
</div>
<% @questions.each do |question| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="program-title">
            <%= question.id %>
          </div>
          <div class="program-body">
            <%= link_to("Show", question_path(question), :class => 'btn btn-info') %>
            <%= link_to("Edit", edit_question_path(question), :class => 'btn btn-info') %>
            <%= link_to("Delete", delete_question_path(question), :class => 'btn btn-danger') %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/questions/new.html.erb
<% @page_title = "Create Question" %>
<div class="center page-header">
  <h2>Create Question</h2>
</div>
	<%= form_for(@question, :url=> questions_path, :method => 'post', :html => {:class => 'form-horizontal', :role => 'form'} ) do |f| %>
      <div class="form-group">
        <%= f.label :description, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :description, class: 'form-control', placeholder: 'Write question description', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :answer, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :answer, class: 'form-control', placeholder: 'Write answer', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :one, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :one, class: 'form-control', placeholder: 'Enter other choice', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :two, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :two, class: 'form-control', placeholder: 'Enter other choice', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :three, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :three, class: 'form-control', placeholder: 'Enter other choice', autofocus: true %>
        </div>
      </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Create Question", class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
	<% end %>

app/views/questions/show.html.erb
<div class="center page-header">
  <h2>Question <%= @question.id %>: <%= @question.description %></h2>
</div>
<div class="well col-xs-8 col-xs-offset-2">
  <table class="table table-bordered table-striped table-hover table-condensed">
    <th class="success text-center">Answer</th>
    <th class="success text-center">One</th>
    <th class="success text-center">Two</th>
    <th class="success text-center">Three</th>
    <tr>
      <td class="active data"> <%= @question.answer %> </td>
      <td class="active data"> <%= @question.one %> </td>
      <td class="active data"> <%= @question.two %> </td>
      <td class="active data"> <%= @question.three %> </td>
    </tr>
  </table>
</div>